version: '3.5'
services:
  mongodb:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    command:
      - 'mongod'
    volumes:
      - mongodb:/data

volumes:
  mongodb:
    driver: local
