version: '3.8'
services:

  mongo-primary:
    container_name: mongo-primary
    image: mongo:4.4    
    volumes:     
      - ~/mongo/data1:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js    
    networks:
      - mongo-network
    ports:
      - 27021:27017  
    restart: always
    environment:
     - MONGO_USER=${MONGO_USER}
     - MONGO_PWD=${MONGO_PWD}
     - MONGO_DB=${MONGO_DB}
    entrypoint:
      [
        "mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs",
      ]    

  mongo-secondary:  
    container_name: mongo-secondary
    image: mongo:4.4
    volumes:
      - ~/mongo/data2:/data/db
    networks:
      - mongo-network
    ports:
      - 27022:27017      
    restart: always
    entrypoint:
      [
        "mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  mongo-arbiter:
    container_name: mongo-arbiter
    image: mongo:4.4
    volumes:
      - ~/mongo/data3:/data/db
    networks:
      - mongo-network
    ports:
      - 27023:27017      
    restart: always
    entrypoint:
      [
        "mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs",        
      ]    

  redis:
    container_name: qso_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/usr/app
    networks:
      - mongo-network

  currency-converter:
    container_name: currency-converter
    build:
      context: .
      dockerfile: ./docker/DockerFile
      target: currency-converter-app    
    ports:
      - 8080:3333
    networks:
      - mongo-network
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter
      - redis    
    environment:
      - DATABASE_URI=${DATABASE_URI}      
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
      - MONGO_DB=${MONGO_DB}
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - EXPRESS_SESSION_SECRET=${EXPRESS_SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}  
    volumes:
      - ./src:/app/src         
      - ./config:/app/config  
      - ./test:/app/test   
      - ./jest.config.ts:/app/jest.config.ts 
      - ./package.json:/app/package.json   
      - ./tsconfig.json:/app/tsconfig.json   
      - ./tsconfig.build.json:/app/tsconfig.build.json    
    command: sh -c "while :; do sleep 1; done"

networks:
  mongo-network:
