version: '3.8'
services:

  mongodb:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    command:
      - 'mongod'
    volumes:
      - mongodb:/data

  redis:
    container_name: qso_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
  mongo-network:
    driver: bridge

volumes:
  mongodb:
    driver: local
