version: '3.5'
services:
  mongodb:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    command:
      - 'mongod'
    volumes:
      - mongodb:/data

  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

# volumes:
#   mongodb:
#     driver: local
#   redis:
#     driver: local