version: '3.8'
services:

  mongodb:
    container_name: database
    image: docker.io/bitnami/mongodb:5.0   
    ports:
      - 27017:27017    
    volumes:
      - mongodb:/data        

  redis:
    container_name: qso_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/usr/app
    networks:
      - app-network 

networks:
  app-network:  

volumes:
  mongodb:
    driver: local
