name: Currency Converter 1.0.0 workflow

run-name: Deploy to ${{ inputs }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - '!master'
    # branches-ignore:    
    #   - master    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node-version: [20.x]

    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      DATABASE_TEST_URI: ${{ secrets.DATABASE_URI }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PWD: ${{ secrets.MONGO_PWD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      API_KEY: ${{ secrets.API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EXPRESS_SESSION_SECRET: ${{ secrets.EXPRESS_SESSION_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}  
   

    services:
      mongo-primary:
        image: mongo:4.4
        ports:
          - 27021:27017

      mongo-secondary:
        image: mongo:4.4
        ports:
          - 27022:27017

      mongo-arbiter:
        image: mongo:4.4
        ports:
          - 27023:27017

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

      currency-converter:
        image: currency-converter-app          
        ports:
          - 8080:3333        

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Docker compose up
        run: |
          docker-compose up -d

      - name: Wait for containers to be ready
        run: |
          until docker-compose ps | grep -q "Up"; do
            sleep 5
          done

      - name: Run unit tests
        run: docker-compose exec -T currency-converter pnpm run test

      - name: Run e2e tests
        env:
          NODE_ENV: test
          DATABASE_TEST_URI: mongodb://admin:admin@mongo-primary:27017,mongo-secondary:27017,mongo-arbiter:27017/test?replicaSet=dbrs
          LOGGER_ENABLED: false
        run: docker-compose exec -T currency-converter pnpm run test:e2e