name: Currency Converter workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variables
        working-directory: ./
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          cat .env      

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}          

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Run unit tests
        working-directory: src
        run: npm run test     

      - name: Run e2e tests
        working-directory: test       
        env:
          DATABASE_URL: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/currency-converter-test    
          LOGGER_ENABLED: false    
        run: npm run test:e2e