name: Currency Converter 1.0.0 workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs: 

  build:
    runs-on: ubuntu-latest

    env:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PWD: ${{ secrets.MONGO_PWD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      API_KEY: ${{ secrets.API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EXPRESS_SESSION_SECRET: ${{ secrets.EXPRESS_SESSION_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}  

    steps:            
    
      - name: Start App
        run: 
          cd $GITHUB_WORKSPACE
          ./scripts/startdb.sh

      - name: Run unit tests        
        run: docker compose exec currency-converter pnpm run test    

      - name: Run e2e tests            
        env:          
          DATABASE_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PWD }}@mongo-primary:27017,mongo-secondary:27017,mongo-arbiter:27017/${{ secrets.MONGO_DB }}?replicaSet=dbrs    
          LOGGER_ENABLED: false    
        run: docker compose exec currency-converter pnpm run test:e2e